### ISSUE TITLE
Code highlighting not working

### ISSUE THREAD

**Issue by allensam** [youngstartupsio/Yeezy-Codes#2]
Idk who set it up but it is not working and needs  to be fixed

**Comment by allensam** [comment]
## Actually we need to remove that from the code because textareas are what we need

[This link](http://www.cdolivet.com/editarea/editarea/exemples/exemple_full.html)
[and](http://codemirror.net/)
[finally](https://ace.c9.io/#nav=about)

**Comment by dinubs** [comment]
it's an issue with the source, it said to be using https instead of http
